// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Service struct {
	ID            uuid.UUID
	CreatedAt     time.Time
	Name          string
	Url           string
	Timeout       int32
	Heartbeat     int32
	Strikes       int32
	WasDown       sql.NullBool
	WhenDown      sql.NullTime
	StrikeCounter sql.NullInt32
	TotalCounter  sql.NullInt32
	DownCounter   sql.NullInt32
}
