// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Service struct {
	ID             uuid.UUID
	CreatedAt      time.Time
	Name           string
	Url            string
	DiscordWebhook string
	Timeout        int32
	Heartbeat      int32
	Strikes        int32
	WasDown        bool
	WhenDown       sql.NullTime
	StrikeCounter  int32
	TotalCounter   int32
	DownCounter    int32
}
