// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: requisitions.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createRequisition = `-- name: CreateRequisition :one
INSERT INTO requisitions (
	id,
	service_id,
	request_time,
	status,
	response_body,
	duration
)
VALUES (
	gen_random_uuid(),
	$1,
	$2,
	$3,
	$4,
	$5
)
RETURNING id, service_id, request_time, status, response_body, duration
`

type CreateRequisitionParams struct {
	ServiceID    uuid.UUID
	RequestTime  time.Time
	Status       int32
	ResponseBody []byte
	Duration     int32
}

func (q *Queries) CreateRequisition(ctx context.Context, arg CreateRequisitionParams) (Requisition, error) {
	row := q.db.QueryRowContext(ctx, createRequisition,
		arg.ServiceID,
		arg.RequestTime,
		arg.Status,
		arg.ResponseBody,
		arg.Duration,
	)
	var i Requisition
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.RequestTime,
		&i.Status,
		&i.ResponseBody,
		&i.Duration,
	)
	return i, err
}

const getFormattedRequisitions = `-- name: GetFormattedRequisitions :many
SELECT (
		SELECT name 
		FROM services
		WHERE service_id = id
	), 
	request_time, 
	status, 
	duration, 
	LENGTH(response_body) 
FROM requisitions
`

type GetFormattedRequisitionsRow struct {
	Name        string
	RequestTime time.Time
	Status      int32
	Duration    int32
	Length      float64
}

func (q *Queries) GetFormattedRequisitions(ctx context.Context) ([]GetFormattedRequisitionsRow, error) {
	rows, err := q.db.QueryContext(ctx, getFormattedRequisitions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFormattedRequisitionsRow
	for rows.Next() {
		var i GetFormattedRequisitionsRow
		if err := rows.Scan(
			&i.Name,
			&i.RequestTime,
			&i.Status,
			&i.Duration,
			&i.Length,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRequisitions = `-- name: GetRequisitions :many
SELECT id, service_id, request_time, status, response_body, duration FROM requisitions
ORDER BY request_time DESC
`

func (q *Queries) GetRequisitions(ctx context.Context) ([]Requisition, error) {
	rows, err := q.db.QueryContext(ctx, getRequisitions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Requisition
	for rows.Next() {
		var i Requisition
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.RequestTime,
			&i.Status,
			&i.ResponseBody,
			&i.Duration,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRequisitionsForService = `-- name: GetRequisitionsForService :many
SELECT id, service_id, request_time, status, response_body, duration FROM requisitions
WHERE service_id = $1
ORDER BY request_time DESC
`

func (q *Queries) GetRequisitionsForService(ctx context.Context, serviceID uuid.UUID) ([]Requisition, error) {
	rows, err := q.db.QueryContext(ctx, getRequisitionsForService, serviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Requisition
	for rows.Next() {
		var i Requisition
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.RequestTime,
			&i.Status,
			&i.ResponseBody,
			&i.Duration,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
