// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: services.sql

package database

import (
	"context"
	"database/sql"
)

const createService = `-- name: CreateService :one
INSERT INTO services (
	id,
	created_at,
	name,
	url,
	timeout,
	heartbeat,
	strikes,
	was_down,
	when_down,
	strike_counter,
	total_counter,
	down_counter
)
VALUES (
	gen_random_uuid(),
	NOW(),
	$1,
	$2,
	$3,
	$4,
	$5,
	$6,
	$7,
	$8,
	$9,
	$10
)
RETURNING id, created_at, name, url, timeout, heartbeat, strikes, was_down, when_down, strike_counter, total_counter, down_counter
`

type CreateServiceParams struct {
	Name          string
	Url           string
	Timeout       int32
	Heartbeat     int32
	Strikes       int32
	WasDown       sql.NullBool
	WhenDown      sql.NullTime
	StrikeCounter sql.NullInt32
	TotalCounter  sql.NullInt32
	DownCounter   sql.NullInt32
}

func (q *Queries) CreateService(ctx context.Context, arg CreateServiceParams) (Service, error) {
	row := q.db.QueryRowContext(ctx, createService,
		arg.Name,
		arg.Url,
		arg.Timeout,
		arg.Heartbeat,
		arg.Strikes,
		arg.WasDown,
		arg.WhenDown,
		arg.StrikeCounter,
		arg.TotalCounter,
		arg.DownCounter,
	)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Name,
		&i.Url,
		&i.Timeout,
		&i.Heartbeat,
		&i.Strikes,
		&i.WasDown,
		&i.WhenDown,
		&i.StrikeCounter,
		&i.TotalCounter,
		&i.DownCounter,
	)
	return i, err
}
